# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:

    - id: check-fmt
      name: Check Go code formatting
      entry: make check-fmt
      language: system
      pass_filenames: false
      always_run: true

    - id: lint
      name: Run linters
      entry: make lint
      language: system
      pass_filenames: false
      always_run: true

    - id: test
      name: Run Go tests
      entry: make test
      language: system
      pass_filenames: false
      always_run: true

